---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: master
        image: zioproto/redis
        imagePullPolicy: Always
        env:
          - name: MASTER
            value: "true"
        ports:
          - containerPort: 6379
        resources:
          limits:
            cpu: "0.9"
        volumeMounts:
          - mountPath: /redis-master-data
            name: redis-master-data
      - name: sentinel
        image: zioproto/redis
        imagePullPolicy: Always
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
        resources:
          limits:
            cpu: "0.9"
      volumes:
        - name: redis-master-data
          persistentVolumeClaim:
            claimName: redis-master-data-pvc
