apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis-slaves
  labels:
    app: rslave
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rslave
  template:
    metadata:
      labels:
        app: rslave
    spec:
      containers:
      - name: slave
        image: zioproto/redis
        imagePullPolicy: Always
        ports:
          - containerPort: 6379
        resources:
          limits:
            cpu: "0.9"
      - name: sentinel
        image: zioproto/redis
        imagePullPolicy: Always
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
        resources:
          limits:
            cpu: "0.9"
