---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis-sentinel
  labels:
    app: redis
spec:
  replicas: 4
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: sentinel
        image: zioproto/redis
        imagePullPolicy: Always
        env:
          - name: SENTINEL
            value: "true"
        ports:
          - containerPort: 26379
        resources:
          limits:
            cpu: "0.9"
