apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-master-lb
    role: service
  name: redis-master-lb
spec:
  ports:
    - port: 6379
      targetPort: 6379
  type: LoadBalancer
  selector:
    app: redis
